#!/usr/bin/env bash

t=$(perl -lne 'print lc($1) if /-\*-(.*)-\*-/ ' $1)
echo pygmentize -f html -O full  -l ${t:-unknown} -o ${1}.html  $1
pygmentize -f html -O full  -l ${t:-unknown} -o ${1}.html  $1
if [ ! $? -eq 0 ]; then
    enscript -E --style=emacs_verbose --color -w html -o ${1}.html $1
fi
