#!/usr/bin/python
# paragrep - trivial paragraph grepper
#
# differs from perl version in parano.
# python version displays paragraph in current file.

import sys, os.path, re
if len(sys.argv)<=1:
	print "usage: %s pat [files]\n" % sys.argv[0]
	sys.exit(1)

pat = sys.argv[1]
try:
	pat_re = re.compile(pat)
except:
	print "%s: bad pattern %s: %s" % (sys.argv[1], pat, sys.exc_info()[1])
	sys.exit(1)
for filename in filter(os.path.isfile,sys.argv[2:]):
	parano = 0
	for para in open(filename).read().split("\n\n"):
		parano += 1
		if pat_re.search(para):
			print filename, parano, para, "\n"
			
